const types = {
    RESET: "RESET",
    FETCH_BOOKS: "FETCH_BOOKS",
    GET_SINGLE_BOOK: "GET_SINGLE_BOOK",
    UPDATE_BOOK: "UPDATE_BOOK",
    DELETE_BOOK: "DELETE_BOOK",
    BOOK_ERROR: "BOOK_ERROR",
    CREATE_BOOK: "CREATE_BOOK",
    ADD_BOOK_TO_USER: "ADD_BOOK_TO_USER",
    FETCH_SINGLE_BOOK: "FETCH_SINGLE_BOOK",
    TOGGLE_MODAL: "TOGGLE_MODAL"
}

export default types;